// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Oracle_Health.Models;

#nullable disable

namespace Oracle_Health.Api.Migrations
{
    [DbContext(typeof(ClinicManagementSystemContext))]
    partial class ClinicManagementSystemContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("DoctorSpecialization", b =>
                {
                    b.Property<long>("DoctorId")
                        .HasColumnType("bigint")
                        .HasColumnName("DoctorID");

                    b.Property<long>("SpecializationId")
                        .HasColumnType("bigint")
                        .HasColumnName("SpecializationID");

                    b.HasKey("DoctorId", "SpecializationId")
                        .HasName("PK__DoctorSp__C840935B79B51BFE");

                    b.HasIndex("SpecializationId");

                    b.ToTable("DoctorSpecializations", (string)null);
                });

            modelBuilder.Entity("Oracle_Health.Models.Appointment", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime");

                    b.Property<long>("DoctorId")
                        .HasColumnType("bigint")
                        .HasColumnName("DoctorID");

                    b.Property<int>("DurationMinutes")
                        .HasColumnType("int");

                    b.Property<long>("PatientId")
                        .HasColumnType("bigint")
                        .HasColumnName("PatientID");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.HasKey("Id")
                        .HasName("PK__Appointm__3214EC0773EDA86F");

                    b.HasIndex("DoctorId");

                    b.HasIndex("PatientId");

                    b.ToTable("Appointments");
                });

            modelBuilder.Entity("Oracle_Health.Models.Doctor", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<long>("UserId")
                        .HasColumnType("bigint")
                        .HasColumnName("UserID");

                    b.HasKey("Id")
                        .HasName("PK__Doctors__3214EC079134ACB4");

                    b.HasIndex("UserId");

                    b.ToTable("Doctors");
                });

            modelBuilder.Entity("Oracle_Health.Models.Notification", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<DateTime?>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<string>("Message")
                        .IsRequired()
                        .IsUnicode(false)
                        .HasColumnType("varchar(max)");

                    b.Property<long>("UserId")
                        .HasColumnType("bigint")
                        .HasColumnName("UserID");

                    b.HasKey("Id")
                        .HasName("PK__Notifica__3214EC071B286F17");

                    b.HasIndex("UserId");

                    b.ToTable("Notifications");
                });

            modelBuilder.Entity("Oracle_Health.Models.Patient", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<long>("Cpr")
                        .HasColumnType("bigint")
                        .HasColumnName("CPR");

                    b.Property<long>("PatientId")
                        .HasColumnType("bigint")
                        .HasColumnName("PatientID");

                    b.Property<long>("UserId")
                        .HasColumnType("bigint")
                        .HasColumnName("UserID");

                    b.HasKey("Id")
                        .HasName("PK__Patients__3214EC0773192BB0");

                    b.HasIndex("UserId");

                    b.HasIndex(new[] { "PatientId" }, "UQ__Patients__970EC347E01B57F5")
                        .IsUnique();

                    b.HasIndex(new[] { "Cpr" }, "UQ__Patients__C1F8973D7E483BA3")
                        .IsUnique();

                    b.ToTable("Patients");
                });

            modelBuilder.Entity("Oracle_Health.Models.Schedule", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<long?>("AppointmentId")
                        .HasColumnType("bigint")
                        .HasColumnName("AppointmentID");

                    b.Property<string>("DayOfWeek")
                        .IsRequired()
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("varchar(20)");

                    b.Property<long>("DoctorId")
                        .HasColumnType("bigint")
                        .HasColumnName("DoctorID");

                    b.Property<DateTime>("EndTime")
                        .HasColumnType("datetime");

                    b.Property<bool?>("IsOnLeave")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<DateTime>("StartTime")
                        .HasColumnType("datetime");

                    b.HasKey("Id")
                        .HasName("PK__Schedule__3214EC0708C8E7C9");

                    b.HasIndex("AppointmentId");

                    b.HasIndex("DoctorId");

                    b.ToTable("Schedules");
                });

            modelBuilder.Entity("Oracle_Health.Models.Specialization", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)");

                    b.HasKey("Id")
                        .HasName("PK__Speciali__3214EC076F44499F");

                    b.ToTable("Specializations");
                });

            modelBuilder.Entity("Oracle_Health.Models.User", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(255)
                        .IsUnicode(false)
                        .HasColumnType("varchar(255)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasMaxLength(255)
                        .IsUnicode(false)
                        .HasColumnType("varchar(255)");

                    b.Property<int>("Role")
                        .HasColumnType("int");

                    b.HasKey("Id")
                        .HasName("PK__Users__3214EC07618DD96A");

                    b.HasIndex(new[] { "Email" }, "UQ__Users__A9D10534E2953B16")
                        .IsUnique();

                    b.ToTable("Users");
                });

            modelBuilder.Entity("Oracle_Health.Models.Visit", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<long>("AppointmentId")
                        .HasColumnType("bigint")
                        .HasColumnName("AppointmentID");

                    b.Property<DateTime?>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<long>("DoctorId")
                        .HasColumnType("bigint")
                        .HasColumnName("DoctorID");

                    b.Property<string>("Notes")
                        .IsRequired()
                        .IsUnicode(false)
                        .HasColumnType("varchar(max)");

                    b.Property<long>("PatientId")
                        .HasColumnType("bigint")
                        .HasColumnName("PatientID");

                    b.Property<string>("Prescription")
                        .IsUnicode(false)
                        .HasColumnType("varchar(max)");

                    b.HasKey("Id")
                        .HasName("PK__Visits__3214EC07B5FD58E4");

                    b.HasIndex("DoctorId");

                    b.HasIndex("PatientId");

                    b.HasIndex(new[] { "AppointmentId" }, "UQ__Visits__8ECDFCA302BD12BD")
                        .IsUnique();

                    b.ToTable("Visits");
                });

            modelBuilder.Entity("DoctorSpecialization", b =>
                {
                    b.HasOne("Oracle_Health.Models.Doctor", null)
                        .WithMany()
                        .HasForeignKey("DoctorId")
                        .IsRequired()
                        .HasConstraintName("FK_DS_Doctor");

                    b.HasOne("Oracle_Health.Models.Specialization", null)
                        .WithMany()
                        .HasForeignKey("SpecializationId")
                        .IsRequired()
                        .HasConstraintName("FK_DS_Specialization");
                });

            modelBuilder.Entity("Oracle_Health.Models.Appointment", b =>
                {
                    b.HasOne("Oracle_Health.Models.Doctor", "Doctor")
                        .WithMany("Appointments")
                        .HasForeignKey("DoctorId")
                        .IsRequired()
                        .HasConstraintName("FK_Appointment_Doctor");

                    b.HasOne("Oracle_Health.Models.Patient", "Patient")
                        .WithMany("Appointments")
                        .HasForeignKey("PatientId")
                        .IsRequired()
                        .HasConstraintName("FK_Appointment_Patient");

                    b.Navigation("Doctor");

                    b.Navigation("Patient");
                });

            modelBuilder.Entity("Oracle_Health.Models.Doctor", b =>
                {
                    b.HasOne("Oracle_Health.Models.User", "User")
                        .WithMany("Doctors")
                        .HasForeignKey("UserId")
                        .IsRequired()
                        .HasConstraintName("FK_Doctor_User");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Oracle_Health.Models.Notification", b =>
                {
                    b.HasOne("Oracle_Health.Models.User", "User")
                        .WithMany("Notifications")
                        .HasForeignKey("UserId")
                        .IsRequired()
                        .HasConstraintName("FK_Notification_User");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Oracle_Health.Models.Patient", b =>
                {
                    b.HasOne("Oracle_Health.Models.User", "User")
                        .WithMany("Patients")
                        .HasForeignKey("UserId")
                        .IsRequired()
                        .HasConstraintName("FK_Patient_User");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Oracle_Health.Models.Schedule", b =>
                {
                    b.HasOne("Oracle_Health.Models.Appointment", "Appointment")
                        .WithMany("Schedules")
                        .HasForeignKey("AppointmentId")
                        .HasConstraintName("FK_Schedule_Appointment");

                    b.HasOne("Oracle_Health.Models.Doctor", "Doctor")
                        .WithMany("Schedules")
                        .HasForeignKey("DoctorId")
                        .IsRequired()
                        .HasConstraintName("FK_Schedule_Doctor");

                    b.Navigation("Appointment");

                    b.Navigation("Doctor");
                });

            modelBuilder.Entity("Oracle_Health.Models.Visit", b =>
                {
                    b.HasOne("Oracle_Health.Models.Appointment", "Appointment")
                        .WithOne("Visit")
                        .HasForeignKey("Oracle_Health.Models.Visit", "AppointmentId")
                        .IsRequired()
                        .HasConstraintName("FK_Visit_Appointment");

                    b.HasOne("Oracle_Health.Models.Doctor", "Doctor")
                        .WithMany("Visits")
                        .HasForeignKey("DoctorId")
                        .IsRequired()
                        .HasConstraintName("FK_Visit_Doctor");

                    b.HasOne("Oracle_Health.Models.Patient", "Patient")
                        .WithMany("Visits")
                        .HasForeignKey("PatientId")
                        .IsRequired()
                        .HasConstraintName("FK_Visit_Patient");

                    b.Navigation("Appointment");

                    b.Navigation("Doctor");

                    b.Navigation("Patient");
                });

            modelBuilder.Entity("Oracle_Health.Models.Appointment", b =>
                {
                    b.Navigation("Schedules");

                    b.Navigation("Visit");
                });

            modelBuilder.Entity("Oracle_Health.Models.Doctor", b =>
                {
                    b.Navigation("Appointments");

                    b.Navigation("Schedules");

                    b.Navigation("Visits");
                });

            modelBuilder.Entity("Oracle_Health.Models.Patient", b =>
                {
                    b.Navigation("Appointments");

                    b.Navigation("Visits");
                });

            modelBuilder.Entity("Oracle_Health.Models.User", b =>
                {
                    b.Navigation("Doctors");

                    b.Navigation("Notifications");

                    b.Navigation("Patients");
                });
#pragma warning restore 612, 618
        }
    }
}
